name = "youtube-caption-generator"
compatibility_date = "2024-02-10"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
name = "youtube-caption-generator-prod"
workers_dev = true
route = "youtube-caption-generator.pages.dev/*"

[env.production.vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "CAPTION_REQUESTS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id" 