name = "youtube-caption-generator"
compatibility_date = "2024-02-10"

[site]
bucket = "./dist"
entry-point = "functions"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "youtube-caption-generator"
workers_dev = true
route = ""
zone_id = ""

# KV Namespace for storing session data
kv_namespaces = [
  { binding = "CAPTION_SESSIONS", id = "your-kv-namespace-id" }
]

# Cron trigger for cleanup
[triggers]
crons = ["0 0 * * *"]  # Run daily at midnight

# Pages configuration
[pages]
pages_build_output_dir = "dist" 